name: Promote Release

on:
  push:
    branches:
      - main

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to push tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get version from package.json
        id: get-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check-tag
        run: |
          TAG=${{ steps.get-version.outputs.TAG }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping promotion."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if tag exists
        if: steps.check-tag.outputs.exists == 'true'
        run: exit 0

      - name: Create tag from package.json version
        run: |
          TAG=${{ steps.get-version.outputs.TAG }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build
        run: |
          mkdir -p release
          cp -r dist/* release/
          zip -r release.zip release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-version.outputs.TAG }}
          name: Release ${{ steps.get-version.outputs.TAG }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
