name: Promotion Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  promote:
    if: startsWith(github.ref, 'refs/tags/v') # ✅ Only run if this is a tag push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build output
        run: |
          mkdir -p release
          cp -r dist/* release/
          zip -r release.zip release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
